### ISSUE TITLE
Should the Facebook Pixel Helper extension be registering the pixel?

### ISSUE THREAD

**Issue by skube** [gabefromutah/gatsby-plugin-facebook-pixel#1]
I've npm installed the plugin and updated my `gatsby-config.js` as outlined in the Readme. I've also installed the Facebook Pixel Helper Extension in my browser. However, I've not seeing any hits on it. 

Using the `react-facebook-pixel` package seems to register the FB Pixel in the extension however.

Is there anything that is required?

**Comment by sarincasm** [comment]
I believe the pixel is inserted into the page only in production mode. So, if you want to test it while developing, you will have to run

```
gatsby build
gatsby serve
```

And then test it out on http://localhost:9000

**Comment by SMerdzhanov** [comment]
Hey @eelsweb, I was looking for answers on another question, but you're kind of right! 

I too followed the setup instructions and this is what I'm getting:
<img width="427" alt="Screen Shot 2019-07-03 at 1 58 18" src="https://user-images.githubusercontent.com/17785884/60552120-43097980-9d36-11e9-96bf-b5832861c62e.png">

I'm a bit concerned by two things:
a) The warning which basically says
```
We detected event code but the pixel has not activated for this event, so no information was sent to Facebook. This could be due to an error in the code, but could also occur if the pixel fires on a dynamic event such as a button click.
```
b) Navigating to a different page and opening the Pixel Chrome Extensions reports there's no Pixel at all.

These both can be just warnings and maybe it's all good, but still would love to hear some feedback.

Thank you for sharing this plugin 🎉

**Comment by gabefromutah** [comment]
I know this is really old, sorry for the delay. Is this still an issue for you?

**Comment by gabefromutah** [comment]
I'm going to go ahead and close this.

**Comment by uriklar** [comment]
I'm having the exact same issue as @SMerdzhanov. The same warning on the main page and on next pages a message that there is not pixel at all..
Did you manage to solve this?

**Comment by uriklar** [comment]
Apparently my adblock was causing this error

**Comment by SMerdzhanov** [comment]
Hey @gabefromutah, sorry for missing your question :see_no_evil:. And I'd agree with @uriklar, that AdBlock is playing some tricks on us :+1: 

Thank you!
