### ISSUE TITLE
Facebook Pixel Standard Events Support

### ISSUE THREAD

**Issue by radhasatam** [gabefromutah/gatsby-plugin-facebook-pixel#4]
Is there a way to include facebook pixel standard events on specific pages? 

Ref: 
[https://www.facebook.com/business/help/402791146561655](https://www.facebook.com/business/help/402791146561655)

**Comment by gabefromutah** [comment]
Not through this plugin. It might be best to call the `fbq` global from the specific page, through `componentDidMount` or `useEffect`. Hope that helps
